# fly.toml app configuration file generated for 3k1watcher on 2024-12-25T00:53:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '3k1watcher'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
